import Head from 'next/head'
import React from 'react'

const Seo = ({title}) => {
  return (
    <React.Fragment>
        <Head>
          <title>{`${title && title + ' |'} CCTV & Security React Next js Template`}</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
    </React.Fragment>
  )
}

export default Seo